### ISSUE TITLE
camera demo

### ISSUE THREAD

**Issue by KiLJ4EdeN** [AmrElsersy/PFLD-Pytorch-Landmarks#1]
Hello 
Thanks for the good work.

I tried the camera demo and the results show that there seems to be a bug,
yaw angles are stable at 13 with a frontal pose and even with moving to the opposite side it won't get higher than 0.
The pitch and roll movements seem to be correct.

Wanted to share this since i have already used the pnp solution with dlib and other landmark models and they seem to be more accurate, whereas the dlib landmarks are known to be very unstable.
Maybe it is because you used 14 points for the projection, again i cannot tell for sure since i have not read your paper.

**Comment by AmrElsersy** [comment]
Thank you so much Abdolkarim :D 

I found the bug, it was an error from the camera demo file, i used the 2D landmarks in a wrong range(the visual range).
It is working now, you can try it, i will be waiting for you, tell me if there is any problem

Thanks again :D

**Comment by KiLJ4EdeN** [comment]
> Thank you so much Abdolkarim :D
> 
> I found the bug, it was an error from the camera demo file, i used the 2D landmarks in a wrong range(the visual range).
> It is working now, you can try it, i will be waiting for you, tell me if there is any problem
> 
> Thanks again :D

You're welcome,

I understand, i did try the new version and it seems more accurate,
Appreciate the quick response.
